ARG BUILD_VERSION=1.0.3
ARG BUILD_PREFIX=/usr/local/sidecar

FROM dbhys/luarocks-builder:5.1 as build-stage

ARG BUILD_VERSION
ARG BUILD_PREFIX

COPY ./rockspec ${BUILD_PREFIX}/rockspec
RUN luarocks install ${BUILD_PREFIX}/rockspec/dbhys-net-simplesidecar-${BUILD_VERSION}-0.rockspec --tree ${BUILD_PREFIX}/deps

# docker build -f Dockerfile-build -t dbhys/net-simplesidecar-build:1.0.3 .
