admin_secret: xxx
proxy:
  listen_port: 8008
  upstream_port: 8025
  #upstream_ip: gateway.docker.internal
  oidc_rs_verifier: 
    enable: true
    issuer: "http://oidc-provider.example.com"
    well_known_uri: "/.well-known/app_oauth_configuration"
    token_header_name: "DBHYS_Authorization"
    checkers: 
      - checker: 
        route: /
        scope: "api.asd a"
      - checker: 
        route: /test2
        scope: api  
        referrer: true
      - checker: 
        route: /test3 
        referrer: true
    
apm:
  enable: true
  collector_url: "http//collector.apm.example.com"
  #instance_name: can_be_a_cluster_name
  client_id: test
  client_secret: xxxxxx